# Generated by Django 5.0.3 on 2024-05-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0007_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferrequest',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
